export LC_CTYPE="en_US.UTF-8"
xset +fp /usr/local/lib/X11/fonts/dina
xset +fp /usr/local/lib/X11/fonts/KanjiStrokeOrders
xset +fp /usr/local/lib/X11/fonts/TrueType
xset +fp /usr/local/lib/X11/fonts/cantarell
xset +fp /usr/local/lib/X11/fonts/freefont
xset +fp /usr/local/lib/X11/fonts/korean
xset +fp /usr/local/lib/X11/fonts/mplus
xset +fp /usr/local/lib/X11/fonts/sazanami
xset +fp /usr/local/lib/X11/fonts/wqy
xset +fp /usr/local/lib/X11/fonts/Droid
xset +fp /usr/local/lib/X11/fonts/ubuntu
xmodmap ~/.Xmodmap
parcellite &
emacs --daemon &
unclutter &
i3
